### ISSUE TITLE
How to execute code?

### ISSUE THREAD

**Issue by ghost** [stuartloxton/aoc-2021#1]
Hey Stuart,

Nice job! I've not dealt with command line stuff in F# before; do you just execute this in F# Interactive? When I try to execute the following:

```
let args = fsi.CommandLineArgs

let ans = 
    System.IO.File.ReadLines(args.[1])
    |> Seq.filter(fun x -> x <> "")
    |> Seq.map int
    |> Seq.windowed 3
    |> Seq.map (fun [|a; b; c|] -> a + b + c)
    |> Seq.pairwise
    |> Seq.fold (fun acc (z1, z2) -> if z2 > z1 then acc + 1 else acc) 0

printfn "Answer: %i" ans;;
```

I get:

stdin(8,21): warning FS0025: Incomplete pattern matches on this expression. For example, the value '[|_; _; _; _|]' may indicate a case not covered by the pattern(s).

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error

I'm probably doing it wrong!

Cheers,

James

**Comment by stuartloxton** [comment]
Hey @jamescodes85,

If you want to run it in F# interactive you should be able to change the `ReadLines` call argument to be a path to the filename (might need a full path if you're not in the same folder, not sure if you're using VisualStudio or something else or how that works), e.g.
```F#
let ans = 
    System.IO.File.ReadLines("input-1.txt")
    ...
```
this is what I was doing when first experimenting with the code.

After I've been running it by opening a command prompt (or powershell), `cd`'ing into the folder with the code and running `dotnet fsi 1.fsx input-1.txt` the fsi.CommandLineArgs should be an array of things after the script name (1.fsx for this one). 

![image](https://user-images.githubusercontent.com/5841/144310683-5a4e0b28-2bfd-4a29-8fcc-22160698dae2.png)

**Comment by ghost** [comment]
Great stuff Stuart, got it running perfectly! This is a great basis for the challenges going forward, so thanks :)
